"""Add Grade model and relationships with User and Course

Revision ID: 89b6035fb115
Revises: a95718ef8187
Create Date: 2025-10-28 23:38:37.252756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b6035fb115'
down_revision = 'a95718ef8187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grades_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_grades_order'), ['order'], unique=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_courses_grade_id'), ['grade_id'], unique=False)
        batch_op.create_foreign_key(None, 'grades', ['grade_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('grade_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_grade_id'), ['grade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_institution_id'), ['institution_id'], unique=False)
        batch_op.create_foreign_key(None, 'institutions', ['institution_id'], ['id'])
        batch_op.create_foreign_key(None, 'grades', ['grade_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_institution_id'))
        batch_op.drop_index(batch_op.f('ix_users_grade_id'))
        batch_op.drop_column('grade_id')
        batch_op.drop_column('institution_id')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_courses_grade_id'))
        batch_op.drop_column('grade_id')

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grades_order'))
        batch_op.drop_index(batch_op.f('ix_grades_name'))

    op.drop_table('grades')
    # ### end Alembic commands ###
